apiVersion: v2
name: havoc
description: Helm chart for deploying havoc (chaos pillar example app)
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../common"
