services:
  nonprod:
    image: docker.io/rancher/k3s:v1.36.2-k3s1
    container_name: k3s-nonprod
    hostname: k3s-nonprod
    privileged: true

    command:
      - server
      - --node-name=nonprod
      - --tls-san=localhost
      - --tls-san=k3s-nonprod

    ports:
      - "6444:6443"

    volumes:
      - nonprod-data:/var/lib/rancher/k3s
      - ./manifests/nonprod:/var/lib/rancher/k3s/server/manifests/custom:ro

    networks:
      - k8s-management

  prod:
    image: docker.io/rancher/k3s:v1.36.2-k3s1
    container_name: k3s-prod
    hostname: k3s-prod
    privileged: true

    command:
      - server
      - --node-name=prod
      - --tls-san=localhost
      - --tls-san=k3s-prod

    ports:
      - "6445:6443"

    volumes:
      - prod-data:/var/lib/rancher/k3s
      - ./manifests/prod:/var/lib/rancher/k3s/server/manifests/custom:ro

    networks:
      - k8s-management

volumes:
  nonprod-data:
  prod-data:

networks:
  k8s-management:
    driver: bridge
