apiVersion: v1
kind: Service
metadata:
  name: {{ include "havoc.fullname" . }}
  labels:
    {{- include "havoc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "havoc.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
